version: "3"
services:
  firefox:
    image: selenium/node-firefox
    volumes:
      - ./selenium/config/firefox:/dev/shm
    depends_on:
      - selenium
    environment:
      HUB_HOST: selenium
    deploy:
      replicas: 5
  chrome:
    image: selenium/node-chrome
    volumes:
      - ./selenium/config/chrome:/dev/shm
    depends_on:
      - selenium
    environment:
      HUB_HOST: selenium
    deploy:
      replicas: 5
  selenium:
    image: selenium/hub
    container_name: selenium
    hostname: qa.local
    ports:
      - 4444:4444
    volumes:
      - ./runtime/selenium.sock:/var/run/docker.sock
      - ./project/1:/test
  security:
    container_name: w9scan
    hostname: qa.local
    ports:
      - 7507:80
    volumes:
      - ./runtime/w9scan.sock:/var/run/docker.sock
    build: ./w9scan
